server:
  port: 4040
  ssl:
    # 改成你的jks文件名
    key-store: classpath:lightblueyzj.cn.jks
    key-store-type: JKS
    #改成你的密钥（设置了密钥就填你的密钥，没有设置就打开keystorePass.txt这个文件，复制里面的密钥）
    key-store-password: t10kl9813i707

http-port: 8080 # http重定向https配置

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://139.196.48.244:4407/employNet
      username: wu
      password: Wzh913000
#  session:
#    store-type: none    #使用jwt进行身份验证，不在保存session
  servlet:
    multipart:
      max-file-size: 10MB   #文件传输大小限制
      max-request-size: 10MB    #请求大小限制


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID      #自动雪花填充id
  mapper-locations: "classpath:/mapper/**/*.xml"

jwt:
  secret-key: "LTAI5tK9FNDQABxM4Rtu3vhE"
  expiration-time: 8640000000  #十天

wechat:
  app-url: "https://api.weixin.qq.com/sns/jscode2session"
  app-id: "wx843ce82edd62d18a"
  app-secret: "3f07f2208a5bca557a121a2e82fb9781"
  avatar-base-path: "D:\\EmployNet\\avatar\\"   #头像存储位置
  annex-base-path: "D:\\EmployNet\\annex\\"     #文件存储位置

